# Generated by Django 5.2.17 on 2026-08-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='confidence',
            field=models.FloatField(blank=True, default=95.0, null=True),
        ),
    ]
